SuperNinjaFat/HDmod

lib/entities/ghost.lua, lib/feelings.lua, lib/hdtype.lua, main.lua
HD_TYPE, Feelings, and ghost behavior methods
=> More refactoring

lib/entities/doors.lua, lib/entities/ghost.lua, lib/entities/idol.lua, lib/entities/olmec.lua, main.lua
Creating doors.lua, refactoring olmec code into its init method
=> Superninjafat

lib/demo.lua, lib/feelings.lua
Set DAR chance back to 12 from 1
I dun goofed 🦗
=> Set DEMO_MAX_WOLRD to 1

lib/entities/acid.lua, main.lua, shaders_mod.hlsl
- Added acid light
- Edited acid.lua file
- Added option to disable acid illumination
- Added shader for particles of the acid
=> Add worm acid light and edit shaders

lib/gen/roomgen.lua, lib/gen/tiledef.lua
changed gen_levelcode_phase_* to one function with phase as param
edited tiledef to use phases = {[1] = {...}, 2...} instead of phase_*
=> refactor roomgen stuff

lib/entities/idol.lua, lib/gen/touchups.lua, lib/spawning/valid.lua
and prevent yetis and landmines from spawning with a tile above
=> implement crockman and bounce trap spawn conditions, fix pushblock spiderweb and tree issue

lib/music/custom_music_engine.lua, lib/music/custommusic.lua, main.lua
This PR replaces the vanilla title screen music with a custom Spelunky HD medley. Unlike the special level music, this music is our own asset and will work automatically without any extra steps from the user.
=> Add custom title music

lib/entities/snow.lua
Adds snowman decorations in snowy ice caves levels. Spawn chance and requirements are based on my own observations, not the actual HD code.
=> Add snowman decorations

lib/entities/snow.lua
Updates snowman spawn chance based on HD data mining.
=> Update snowman spawn chance

lib/entities/snow.lua
Created a system that dynamically modifies the snow effect used in Ice Caves into a heavy snow effect similar to the one in HD for snowing levels.
=> Added heavy snow effect

lib/entities/snow.lua, lib/entities/snowball.lua, lib/feelings.lua
Update feelings.lua:
- Add commented out 1 and 0 chance bools for easy debugging
- Remove SNOWING level feeling in favor of SNOW
=> (I-7) Merge SNOW and SNOWING level feeling

lib/entities/alienlord.lua, lib/gen/backwall.lua
Added a basic background for the UFO and fixed the alienlord from not facing left in the UFO subchunk
=> UFO background, alienlord fix

lib/entities/tree.lua
=> Fix tree vines removal

lib/entities/black_knight.lua, lib/entities/green_knight.lua
Finished up tweaking the black knight AI and gave both the black knight and green knight jingly jangly armor SFX
=> Black Knight AI polish, Green Knight SFX

lib/entities/black_knight.lua, lib/entities/green_knight.lua
Changed the method for detecting if the green knight should flip to use a much more accurate method, and removed some code from when I was testing out the green knight changes.
=> Adjusted flipping method for black knight, fixed green knight testing

lib/gen/touchups.lua, main.lua
=> add DAR fog, remove worm fog

lib/entities/tree.lua, lib/gen/roomdef.lua, lib/spawning/valid.lua
Prevent DAR decoration from spawning in water,
Increase the chance of faces on trees in DAR,
Prevent the tomb room from spawning twice in a run
=> DAR improvements

lib/entities/idol.lua, lib/entities/wormtongue.lua
Remove whitespace in wormtongue library
=> Add effects to jungle idoltrap, reduce timeout

lib/feelings.lua, lib/spawning/create.lua, lib/spawning/spawndef.lua, lib/spawning/valid.lua
Remove old creation methods in create library
Fix temple's vault getting set to olmec
=> Scorpionfly, devil, imp spawns

lib/gen/touchups.lua, main.lua
Add ambiance sounds to the door to jungle from mines, and to the door from ice caves to temple
Closes #96
=> Add door ambiance sounds

lib/entities/piranha.lua
=> Piranhas no longer target dead players

lib/gen/touchups.lua, lib/spawning/valid.lua, main.lua
=> Dark level torches, optimize is_solid_grid_entity

lib/entities/shops.lua, lib/gen/decor.lua, lib/gen/roomgen.lua, lib/gen/s2roomctx.lua
Fix gambling shops in and outside of the blackmarket using the wrong shop template
Fix decorations in Black Market
(However the Black Market gambling shop still has issues)
=> Fix Gambling shop bugs

lib/entities/bacterium.lua
=> Make bacterium edible to mantraps

lib/common.lua, lib/entities/alientank.lua, lib/entities/animation.lua, lib/entities/baby_worm.lua
Closes #176
Also changed some stuff of the alien tank to reuse some code and of the animation lib
In hd it seems that baby worms continue having velocity after touching a wall on air (without changing direction), I probably should implement that
=> Improve baby worm

lib/gen/touchups.lua
=> fix worm gapblock with pre_entity_spawn

lib/common.lua
Now supports custom and vanilla sounds alike, looped or not. Also more options for adjusting how far away your sound should be heard.
=> Refactored play_sound_at_entity

lib/common.lua, lib/entities/alienlord.lua, lib/entities/alientank.lua, lib/entities/bacterium.lua, lib/entities/black_knight.lua, lib/entities/critterrat.lua, lib/entities/devil.lua, lib/entities/giant_frog.lua, lib/entities/green_knight.lua, lib/entities/hawkman.lua, lib/entities/hell_miniboss.lua, lib/entities/idol.lua, lib/entities/laser_turret.lua, lib/entities/liquid.lua, lib/entities/mammoth.lua, lib/entities/piranha.lua, lib/entities/scorpionfly.lua, lib/entities/snowball.lua, lib/entities/spikeball_trap.lua, lib/entities/succubus.lua, lib/entities/web_ball.lua, lib/entities/wormtongue.lua
Reverts SuperNinjaFat/HDmod#275
=> Revert "play_sound_at_entity Refactor: The Definitive Edition™"

lib/entities/liquid.lua
=> fix liquid illumination still being updated after liquid doesn't exist

lib/entities/arrowtrap.lua, lib/entities/pushblock.lua
Also do the same to gold pushblocks
=> Make gold arrow traps drop a gold nugget

lib/entities/damsel.lua, lib/entities/hideyhole.lua
This should fix the nolevel bugs in temple
=> Set damsel type inside create_damsel

lib/spawning/valid.lua
Prevent tikitraps from spawning embedded into idoltrap floors Add tikivillage paths to generic trap room filter
=> Add more fixes for tikitrap gen

lib/entities/idol.lua, lib/gen/roomdef.lua
Don't listen to one of those commit names, that's a lie, it actually slows it down!
=> Decrease temple idoltrap speed

lib/entities/mines_deco.lua, lib/entities/shops.lua, lib/entities/tombstone.lua, lib/gen/touchups.lua, lib/spawning/embed.lua, lib/spawning/remove.lua, lib/spawning/valid.lua, main.lua
Closes #148
- ~~Provide an option to revert to S2 item pools, with the only exception being the skeleton key, since that does nothing in our mod~~
Preventing only the skeleton key from spawning in s2 item pools may take some unnecesary effort, so idk if do that, or maybe leave it for later
=> HD item pools pt.2

lib/common.lua, lib/entities/scorpionfly.lua
Adds new scorpionfly behiavor when idle, based on the HD one
Also fixes a few bugs, and gives correct behavior when frozen, hit by camera, or stuck on web
I noticed there's a TODO about the rubble color, but it seems quite good for me, idk what anyone else thinks about it
Closes #282
=> Scorpionfly flying behavior, fix some bugs

lib/spawning/create.lua, lib/spawning/valid.lua
=> fix anubis spawn validation, spawn only on path

lib/entities/hawkman.lua
Also remove legacy code from black knight code
=> Prevent hawkman from picking up items

lib/entities/idol.lua
This error doesn't really affect the mod but just annoys me when reloading the mod :cat2:
=> fix annoying error when reloading script via ctrl+f5

lib/spawning/remove.lua, lib/spawning/spawndef.lua, main.lua
There's a little issue with the debbuging spawn stuff, since even when setting the chance to zero, the game will still call the is_valid functions
=> Update remove floors fn and spawn traps on post_spawn_traps

lib/entities/cog_door.lua, lib/feelings.lua, lib/spawning/remove.lua, lib/spawning/spawndef.lua, lib/spawning/valid.lua
=> Redo COG door entrance spawn

lib/music/custom_music_engine.lua
This PR fixes a couple minor custom music issues:
- Fixed custom music in shops (more accurate camera check, and fixed not playing in shops owned by a hostile vendor).
- Fixed custom music playing during ankh cutscene.
=> Fix custom music for shops and ankh cutscene

lib/entities/sliding_wall.lua, lib/gen/touchups.lua
- Fix a console error when leaving the haunted castle without triggering the sliding door
- Change all altar damage spawns to spiders
=> Remove beg quest, include a few other fixes

lib/feelings.lua, lib/gen/roomgen.lua, main.lua
- Fix feelings toast messages not being shown, due to them being replaced by `nil` messages of other level feelings
- Set a feeling priority based on HD's
=> Fix feelings toast

lib/entities/shops.lua, main.lua
- There were bet machines spawning for each shop in black market, remove all except one, and place it correctly
- The owner shopkeeper of the dice shop was the ankh shopkeeper, fixed that too
=> Fix black market dice shop

lib/spawning/valid.lua
=> Fix black market entrance spawning on traps/tombstones

lib/entities/wormtongue.lua
- Make wormtongue to move entities sticked to it like on HD, and move them down if has enough velocity
- Fix position accidentally being lower since past commit (#167) which set the `orig_y` to the position before it was moved `1.15` higher, it and just adjusted the bg lower instead of changing the tongue position. Note: now I move the tongue last part instead of the floor, so position is relative to the floor overlay
=> Worm tongue improvements

lib/entities/wormtongue.lua
Clean up the code, use the animation library, fix several bugs
=> Revise wormtongue code

lib/gen/backwall.lua, lib/gen/tiledef.lua
=> remove backgrounds overlapping script spawned ones

lib/gen/touchups.lua, lib/music/mines/minesmusic.lua
Corrects the length of Cap A6.
Comments out the embed debug message.
=> Fix Cap A6 length, disable embed message

lib/music/mines/minesmusic.lua
Temporarily removes fills and caps from mines music
=> Remove mines music fills and caps
