SuperNinjaFat/HDmod

main.lua

Restoring fake 1-4 fixes shops spawning on 1-4 and prevents the game forcing exit doors on the right side of the level to go to Volcana.
The testing room now correctly has 2 levels and exiting 1-2 sends you back to camp. Whoever works on enemy spawning next should be free to edit HD_ROOMOBJECT.TESTING[2] level structure for testing out procedural spawns (which can be enabled with room_gen_ctx:set_procedural_spawn_chance() placed in testroom_level_2())

Restore fake 1-4, fix testing room level progression

---

lib/music/custom_music_engine.lua
lib/music/custommusic.lua
main.lua

This PR adds scripted music to the worm, black market, yeti kingdom, and mothership levels. The worm plays the giant frog music, while the others play their respective themes from Spelunky 2's soundtrack. My custom music engine isn't a perfect replica of the vanilla music engine, but it's decently close and I might find ways to improve it in the future.
This PR does not include the raw audio files for these music tracks. You need to extract the audio files locally using Modlunky's "Extract Assets" feature with "Extract .ogg files" enabled. Nothing breaks if you don't have the files extracted locally; the special levels just play their usual vanilla music instead. I still want to look into whether it's possible to play these music tracks directly out of the soundbank without needing to …

Add scripted music for special levels

---

main.lua

This PR fixes an issue where custom title music would sometimes not play the first time the title screen was loaded. Specifically, in the Playlunky nightly, the `LOADING` callback for the title screen doesn't execute for certain loading values when the game is first loaded, which was a callback the custom music engine was depending on.

Fix custom title music sometimes not playing on first title screen

---

lib/spawning/valid.lua

Make mammoth spawn method avoid the right psychic presence room, require 2 floors underneath and 4x2 tiles free.

(I-9) Update mammoth spawn validation method

---

Data/Levels/icecavesarea.lvl

The Ice Caves level gen crash seems to be caused by the procedural spawn "hd_procedural_wetfur_landmine". Unless this is set to 0, you're prone to Ice Cave crashes.

"fixed" the Ice Caves level gen crash

---

Data/Levels/icecavesarea.lvl

Turns out all the wetfur stuff is causing crashes in Ice Caves. We're disabling them for now

Further work on Ice Caves crash

---

lib/feelings.lua

The Moai head will spawn on 3-4 if the player went to the Worm or Mothership on 3-3.

Added edge case for 3-4 Moai

---

lib/entities/laser_turret.lua
lib/entities/snowball.lua

The turret laser wasn't assigned ownership correctly, and the other bug was caused by snowball code that affected all ROCK entities, including the turret that uses ROCK as base.
Also renamed a function and moved/added some comments

Fix laser turret ownership and a bug caused by snowball

---

lib/entities/custom_death_messages.lua
lib/entities/wormtongue.lua

Improved the rubble for the worm emerging, increased the radius, stopped using a boulder for the sound and screen shake, added jiggle physics to the worm tongue and fixed a bug where held items were still visible once consumed by the worm. Also tweaked a small issue regarding custom death messages in The Worm

Worm Tongue revisions

---

lib/entities/crysknife.lua

- Fix crysknife bug when a character with it dies (if another character uses the whip, it will spawn the crysknife on the dead one)
- Add crysknife to entity spawner
- Change indentation on the file to be of the same style

Fix crysknife bug and add to entity spawner

---

lib/entities/botd.lua
lib/entities/idol.lua
lib/feelings.lua
lib/flags.lua

Added a function that overrides any previously existing toast / speechbubble and displays the newly called one, this should hopefully fix some of the problems we've had with these messages not displaying properly.

toast_override function

---

lib/gen/touchups.lua
main.lua

- Change tikimen wooden shields to boomerangs on post level generation
- Renamed the fix door ambient sound function
Closes #212

Replace tikimen wooden shields with boomerangs, rename function

---

lib/spawning/remove.lua

Diagonal neighbor floors weren't getting fixed, resulting on incorrect floor textures, some more noticeable than others
This is an image showing how it was before this PR

Fix diagonal neighbor floors on remove_floor_and_embedded_at function

---

lib/spawning/valid.lua

Prevent tikitraps from spawning where there are blocks on either side of its top part
Restrict tikitraps to only spawn in certain rooms
Add altar tiles to bm entrance valid method

Improve enemytikitrap jungle validation method

---

lib/entities/tree.lua
lib/gen/roomgen.lua
lib/gen/tiledef.lua
lib/gen/touchups.lua
lib/spawning/create.lua
main.lua

- Fix small error with dark level wall torches
- Changed `spawn_grid_entity` on some monsters to `spawn_on_floor`
- Moved decorate_trees to POST_LEVEL_GENERATION to prevent vine visibility on first frame
- Moved elevator tilecode to phase 3 to prevent it looking like a pushblock on first frame
- Removed level generation phase 4

Small fixes

---

lib/entities/wormtongue.lua

Prevents beehive from removing the tongue bg and fixes the issue of not being able to enter the worm if the bg is removed somehow
Closes #268

fix worm entrance bg error

---

lib/common.lua
lib/entities/alienlord.lua
lib/entities/alientank.lua
lib/entities/bacterium.lua
lib/entities/black_knight.lua
lib/entities/critterrat.lua
lib/entities/devil.lua
lib/entities/giant_frog.lua
lib/entities/green_knight.lua
lib/entities/hawkman.lua
lib/entities/hell_miniboss.lua
lib/entities/idol.lua
lib/entities/laser_turret.lua
lib/entities/liquid.lua
lib/entities/mammoth.lua
lib/entities/piranha.lua
lib/entities/scorpionfly.lua
lib/entities/snowball.lua
lib/entities/spikeball_trap.lua
lib/entities/succubus.lua
lib/entities/web_ball.lua
lib/entities/wormtongue.lua

play_sound_at_entity is now deprecated, still works but throws a warning message when used. Added two new functions to replace it: play_vanilla_sound and play_custom_sound, same arguments as play_sound_at_entity but with a 4th one for if the sound loops or not.
Also went and swapped out every single play_sound_at_entity call with either play_vanilla_sound or play_custom_sound. All custom sounds were also converted to use play_custom_sound.
The Succ was also updated to fix the animations and give her the ability to be stunned
Fixed succubus debug spawn

Play sound at entity refactor

---

lib/entities/king_yama.lua
lib/options.lua

Increase the velocity of the falling skulls
Lower yama phase1 smash agro by 1 tile to match his phase 2 agro, which activates when the player is on the throne floor. Change boss debug warp names to OLMEC and YAMA

Apply minor yama fixes

---

lib/music/custom_music_engine.lua
lib/music/custommusic.lua
lib/music/hell/hellmusic.lua
main.lua

This PR updates the custom music system to allow music to play uninterrupted through level transitions. Currently, this only affects the custom hell music. It also slightly reduces the volume of the custom hell music, which was significantly louder than the rest of the game music.

Play custom music in level transitions

---

lib/entities/devil.lua

This didn't resolve the issues with devil behavior while frozen. This will have to be handled extensively later.

Revert devil frozen fix from 4497c90

---

lib/ending.lua
lib/entities/doors.lua
lib/entities/king_yama.lua
lib/entities/olmec.lua
main.lua

This PR fixes several things relating to the win screen and boss exit doors. It is now possible to play a run from start-to-end at Olmec. If the book of the dead is granted via debug settings, the run can reach the Yama ending.
* Olmec win screen no longer crashes.
* Yama win screen is functional.
* Hell door in Olmec level goes to hell instead of the win screen.
* Boss exit doors no longer always use the Hundun ending.
* Boss exit doors refactored to function like vanilla boss exits.
* Yama exit door unlocks when Yama is defeated.
* Boss exit doors visually appear unlocked if the debug setting to unlock them is enabled.
The goal of this PR was just to get a minimally functional start-to-end run. The ending sequences are still mostly vanilla and will need much more work to resemble the HD …

Fix win screen and boss exit doors

---

lib/entities/anubis2.lua
lib/entities/botd.lua
lib/entities/doors.lua
lib/options.lua

- Use custom entities lib for the items
- Change anubis 2 red skeleton spawn conditions and fix failsafe bug
- Make anubis 2 invulnerable to lava
- Added setting to increase level count when warping, since not doing so when level count is still zero, triggers ON.START callbacks 
I still want to revise anubis 2 spawn when he follows through levels, I think it's a bit different from HD now (in HD he spawns 2 tiles above instead of on the same pos as player iirc)

 Update BOTD, other changes

---

lib/music/mines/minesmusic.lua

Prevent the mines idle and lowhp stems from playing immediately after the intro stems.

prevent idle stems from playing after intro

---

lib/entities/critterfrog.lua
lib/entities/doors.lua
lib/entities/shops.lua

Prevent access to hell depending on demo limit
Also remove dice and board up bm dice shop (temporarily until we can fix it)
Make frog critter jump only when on floor

Prevent hell demo access

---

lib/gen/roomgen.lua
lib/spawning/spawndef.lua
lib/spawning/valid.lua
main.lua

- Make trap spawns have a specific order, prevent traps from spawning on specific rooms (shops, entrance, vault, same as procedural spawns)
- Fix tikitraps spawning on activefloors and pushing them to the side
- Move `assign_s2_level_height` to `main.lua` callback, move check of `set_chances` to be done on `main.lua`

Small improvements n fixes

---

lib/gen/touchups.lua
main.lua

This PR sets up magmar spawn logic for Temple, CoG, Olmec, and Hell. It uses the same logic object as the vanilla game, with all the same rules, spawn timings, and quirks.

Add magmar spawn logic

---

lib/entities/liquid.lua

It may only have crashed when warping via OL, but still had to be fixed
Also fixes illumination disappearing when opening settings

fix liquid illumination crash

---

lib/entities/shops.lua
main.lua

- Changes back shopkeeper spawn to be spawn normally by the game, fixing bomb detection area
- To prevent the shopkeeper dialogs, zoom and sounds, just enabled the black market presence flag
- Edited ankh shop to be a bit more higher by using `SHOP_BASEMENT` room template and added some bg
- Also edited the spawn of the `DECORATION_SHOPFORE` a bit
Closes #445

Fix bm shop bomb detection, edit ankh shop

---

lib/credits.lua
lib/entities/camel.lua

This PR fixes the credits music resetting when pressing jump, and reduces some jank with how the rope input was being used to skip it.

Fix credits screen skip behavior
